### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by garyb**
Or would `Conjunctive` and `Disjunctive` be better?

I'll leave this unmerged until we release a new psc.

### CODE REVIEW

**Comment by paf31** [comment]
Looks good. More options for names:

- `Sup` and `Inf` (:+1:)
- `Meet` and `Join`
- `Max` and `Min`

**Comment by paf31** [comment]
I'm fine with this as is by the way. Just making some alternative suggestions..

**Comment by garyb** [comment]
Yep, I got that :) Will probably go with the `Sup` or `Meet` versions too, they're easier to type ;)

**Comment by garyb** [comment]
For purescript/purescript#1038

**Comment by paf31** [comment]
So did you get the command line tool running then?

**Comment by garyb** [comment]
Not yet, just remembered I'd opened this and it falls in with the other things that are pending.

**Comment by garyb** [comment]
I'm actually thinking this round might be a case for doing it manually again - a lot of stuff needs fixing, not just bumping. I'm replacing uses with `Number` with `Int` where it should be used (like in `replicateM`), and also making the change to `Lazy` you suggested a while back, where we drop `Lazy1`, `Lazy2`, etc in favour of using `Lazy (f a)` style constraints.

**Comment by garyb** [comment]
Renamed to `Sup`/`Inf`.

**Pull request merged**
