### PR TITLE
Add invariant instances

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by paf31** [comment]
:+1: but...

- Defining an instance of `Invariant` for things which are already `Functor` or `Contravariant` seems a little odd to me. Sure, they are valid instances, but it seems almost misleading to define them, since we can say something stronger. Anything we can do with an `Invariant`, we can also do with a `Functor`, so we don't lose anything. I'm not sure what to do about this, just saying.
- Should these instances be here or in `purescript-invariant`? I don't feel too strongly either way, again, just seemed worth bringing up.

Generally, I feel awkward about `Invariant` things. What is their categorical interpretation? It seems like it would almost always be better to talk about the "trace" of a profunctor:

```
newtype Trace p a = Trace (p a a)
```

and then to use the profunctor machinery. e.g. `Endo` is isomorphic to `Trace (->)`.

**Comment by garyb** [comment]
- Did you see purescript/purescript-invariant#1? That's another potential solution for avoiding explicit `Functor` instances, so would only require the `Endo` instance here.
- I thought we were defining instances with their `data` declarations wherever it was possible - I don't really mind either way either.

In categorical terms `Invariant` is an [exponential functor](https://proofwiki.org/wiki/Definition:Exponentiation_Functor), but I don't really know what that means. ;)

The `Trace` approach does seem appealing, but that would prevent us from actually making an instance for `Endo` right? Likewise, defining instances for [things like this](https://github.com/purescript-contrib/purescript-strongcheck/blob/83d10dee2a370bd5d77c9d2ba2e98a5b76516372/src/Test/StrongCheck/Perturb.purs#L54-L58).

Perhaps @jdegoes has some thoughts on this too?

**Comment by paf31** [comment]
So I think "the" exponential _functor_ (which is just `r ->` in PureScript terms) is different from "a" _exponential functor_ as the term is used, for example, [here](http://comonad.com/reader/2008/rotten-bananas/). I still don't really know what the categorical counterpart of this is, but that doesn't make it a bad abstraction.

My goal with something like `Trace` would be to force users to map from `Endo` to `Trace (->)`, do work, and then map back, probably with `Endo` as a newtype for `Trace (->)`.

I think this looks good though, let's merge it.

**Comment by paf31** [comment]
Another thought: `Endo` is actually a better name for `Trace`. Maybe we should change `Endo a` to `Endo k a` and add `Category a => Monoid (Endo a)`? Then we get `Semigroup` from `Semigroupoid` too.

I think there is a way to construct a canonical `Profunctor` from any `f`, I'm going to think about it.

**Comment by paf31** [comment]
A little factoid which seems relevant:

For every `Profunctor` `p` there is an `Invariant` functor `Endo p` given by

```purescript
newtype Endo p a = Endo (p a a)
```

This gives a functor from the category of profunctors to the category of functors. But we can go the other way too. Given a functor `f` we can form a valid `Profunctor` in a Yoneda-lemma-kinda way as follows:

```
data Proneda f where
  Proneda :: f x -> (a -> x) -> (x -> b) -> Proneda f a b

instance Profunctor (Proneda f) where
  dimap l r (Proneda fx f g) = Proneda fx (l >>> f) (g >>> r)

liftProneda :: forall f a. f a -> Proneda f a a
liftProneda fa = Proneda fa id id
```

`Proneda f` is a `Profunctor` for any `f`, not just `Invariant` `f`s. But if `f` is `Invariant`, we can map back too:

```
lowerProneda :: forall f a. (Invariant f) => Proneda f a a -> f a
lowerProneda (Proneda fx f g) = imap f g fx
```

I claim that `Proneda` is right adjoint to `Endo`, i.e. it is a _free_ `Profunctor` for a functor, and in the case of an `Invariant f`, `liftProneda` and `lowerProneda` are inverses. I haven't proved this yet...

So my conjecture is that whenever you have a thing and you think `Invariant` is useful, it's just as useful to work with `Proneda f` instead.

**Comment by jdegoes** [comment]
@paf31 On the ways in which invariant functors compose....

We can define `InvariantApply`:

```purescript
class (Invariant f, Zip f) <= InvariantApply f where
  iap1 :: forall a b. f (Iso a b) -> f a -> f b
```

This is the invariant analogue of `Apply`. There's a further abstraction, let's call it `InvariantApplicative`, which lets you lift pure values:

```purescript
class (InvariantApply f) <= InvariantApplicative f where
  ipure :: forall a. f a
```

Let's say our invariant functor is `data App i = App (i -> HTML i)`. The above sorts of abstractions let you combine `App i` and `App j` into `App (Tuple i j)`, as well as imap that `Tuple i j` to anything it is isomorphic to (e.g. exchanging between tuple encodings and a product type). Which is about the best you can hope for, and actually pretty useful.

I wonder what these things would look like under your `Proneda`, and in particular if that formulation would simplify anything...

**Comment by paf31** [comment]
It seems like `Apply` corresponds to `(***)` under the `Proneda` mapping.

I'm not saying this isn't a useful abstraction, but I don't think it adds anything over `Profunctor`.

Its categorical interpretation seems to be "a functor in the category of objects and isomorphisms" - is that right? If so, it makes sense to me to keep this disjoint from the `Functor`/`Applicative` etc. hierarchy. It would be nice to be able to unify the two using `PolyKinds`, but that's a long way off yet.

**Comment by jdegoes** [comment]
Yes, that's right. I've often thought one could get some mileage out of just generalizing the arrows in these categorical abstractions, e.g. something like:

```purescript
class Functor p f where
  (<$>) :: forall a b. p a b -> f a -> f b
```

Though haven't really given it enough thought to say if it would be useful.

**Comment by paf31** [comment]
It's definitely useful: http://blog.functorial.com/posts/2012-02-02-Polykinded-Folds.html

I'd like to think what folds in the `Invariant` category would look like actually.

I've been thinking about polykinds quite a bit lately. It shouldn't be too hard to implement them. The tricky bit is when values need to depend on the kind of their polykinded type, which gets a bit weird. Maybe I could just avoid that case for now, and require extra annotations.

**Pull request merged**
